#include "libft.h"
#include "string.h"

int		main(void)
{
	char	*s1 = "\t\v\f\r\n \f-06050";
	char	*s2 = "\t\v\f\r\n \f \f\t\n\r    06050";
	char	*s3 = "ABC123";
	char	*s4 = "123ABC";
	char	*s5 = "A1B2C3";
	char	*s6 = "1A2B3C";
	char	*s7 = "abc123";
	char	*s8 = "-06050\t\v\f\r\n \f";
	char	*s9 = "  06050\t\v\f\r\n \f \f\t\n\r  ";
	char	*s10 = "+42";
	char	*s11 = "\20042";
	char	*s12 = "0001020304";
	char	*s13 = "+1234";
	int		st1 = atoi(s1);
	int		ft1 = ft_atoi(s1);
	int		st2 = atoi(s2);
	int		ft2 = ft_atoi(s2);
	int		st3 = atoi(s3);
	int		ft3 = ft_atoi(s3);
	int		st4 = atoi(s4);
	int		ft4 = ft_atoi(s4);
	int		st5 = atoi(s5);
	int		ft5 = ft_atoi(s5);
	int		st6 = atoi(s6);
	int		ft6 = ft_atoi(s6);
	int		st7 = atoi(s7);
	int		ft7 = ft_atoi(s7);
	int		st8 = atoi(s8);
	int		ft8 = ft_atoi(s8);
	int		st9 = atoi(s9);
	int		ft9 = ft_atoi(s9);
	int		st10 = atoi(s10);
	int		ft10 = ft_atoi(s10);
	int		st11 = atoi(s11);
	int		ft11 = ft_atoi(s11);
	int		st12 = atoi(s12);
	int		ft12 = ft_atoi(s12);
	int		st13 = atoi(s13);
	int		ft13 = ft_atoi(s13);

	ft_putstr("ST1: ");
	ft_putnbr(st1);
	ft_putchar('\n');
	ft_putstr("FT1: ");
	ft_putnbr(ft1);
	ft_putchar('\n');
	ft_putstr("ST2: ");
	ft_putnbr(st2);
	ft_putchar('\n');
	ft_putstr("FT2: ");
	ft_putnbr(ft2);
	ft_putchar('\n');
	ft_putstr("ST3: ");
	ft_putnbr(st3);
	ft_putchar('\n');
	ft_putstr("FT3: ");
	ft_putnbr(ft3);
	ft_putchar('\n');
	ft_putstr("ST4: ");
	ft_putnbr(st4);
	ft_putchar('\n');
	ft_putstr("FT4: ");
	ft_putnbr(ft4);
	ft_putchar('\n');
	ft_putstr("ST5: ");
	ft_putnbr(st5);
	ft_putchar('\n');
	ft_putstr("FT5: ");
	ft_putnbr(ft5);
	ft_putchar('\n');
	ft_putstr("ST6: ");
	ft_putnbr(st6);
	ft_putchar('\n');
	ft_putstr("FT6: ");
	ft_putnbr(ft6);
	ft_putchar('\n');
	ft_putstr("ST7: ");
	ft_putnbr(st7);
	ft_putchar('\n');
	ft_putstr("FT7: ");
	ft_putnbr(ft7);
	ft_putchar('\n');
	ft_putstr("ST8: ");
	ft_putnbr(st8);
	ft_putchar('\n');
	ft_putstr("FT8: ");
	ft_putnbr(ft8);
	ft_putchar('\n');
	ft_putstr("ST9: ");
	ft_putnbr(st9);
	ft_putchar('\n');
	ft_putstr("FT9: ");
	ft_putnbr(ft9);
	ft_putchar('\n');
	ft_putstr("ST10: ");
	ft_putnbr(st10);
	ft_putchar('\n');
	ft_putstr("FT10: ");
	ft_putnbr(ft10);
	ft_putchar('\n');
	ft_putstr("ST11: ");
	ft_putnbr(st11);
	ft_putchar('\n');
	ft_putstr("FT11: ");
	ft_putnbr(ft11);
	ft_putchar('\n');
	ft_putstr("ST12: ");
	ft_putnbr(st12);
	ft_putchar('\n');
	ft_putstr("FT12: ");
	ft_putnbr(ft12);
	ft_putchar('\n');
	ft_putstr("ST13: ");
	ft_putnbr(st13);
	ft_putchar('\n');
	ft_putstr("FT13: ");
	ft_putnbr(ft13);
	ft_putchar('\n');
	return (0);
}
